name: Deploy to CSE125 Server

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: "jessieou"  
        SERVER_PORT: "222"
        REMOTE_PATH: "/var/www/html/class/cse125/www/2025/cse125g3/group3-website"
      run: |
        # Set up SSH configuration
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Copy files using SCP
        scp -r -P $SERVER_PORT -o StrictHostKeyChecking=no \
            * $SERVER_USER@cse125.ucsd.edu:$REMOTE_PATH
