name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          set -x
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/github-actions"
          chmod 600 "$HOME/.ssh/github-actions"
          echo "Host: ${{ secrets.SSH_HOST }}"
          ssh-keyscan -v -H ${{ secrets.SSH_HOST }} >> "$HOME/.ssh/known_hosts"

      - name: Test SSH connection
        run: |
          ssh -i $HOME/.ssh/github-actions -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "echo connected"



      - name: Deploy via rsync
        run: |
          rsync -avz --no-perms --no-owner --no-group --exclude=".git" -e "ssh -i $HOME/.ssh/github-actions" ./ ${SSH_USERNAME}@${SSH_HOST}:/var/www/html/class/cse125/www/2025/cse125g3/group3-website
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}


