name: Deploy to CSE125 Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: "jessieou"
        SERVER_PORT: "222"
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/cse125_id_rsa
        chmod 600 ~/.ssh/cse125_id_rsa
        
        # Add server fingerprint to known_hosts
        ssh-keyscan -p $SERVER_PORT cse125.ucsd.edu >> ~/.ssh/known_hosts
        
        # Create SSH config
        echo "Host cse125
          HostName cse125.ucsd.edu
          Port $SERVER_PORT
          User $SERVER_USER
          IdentityFile ~/.ssh/cse125_id_rsa
          StrictHostKeyChecking=yes
          UserKnownHostsFile ~/.ssh/known_hosts" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Deploy via Rsync
      env:
        REMOTE_PATH: "/var/www/html/class/cse125/www/2025/cse125g3/group3-website"
      run: |
        rsync -avz --delete -e "ssh -F ~/.ssh/config" \
            ./ cse125:$REMOTE_PATH/
