name: Deploy to CSE125 Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SERVER_USER: "jessieou"
        SERVER_PORT: "222"
      run: |
        # Create SSH directory structure
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Add private key
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/cse125_id_rsa
        chmod 600 ~/.ssh/cse125_id_rsa

        # Add known hosts entry
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        # Create SSH config
        cat << EOF > ~/.ssh/config
        Host cse125
          HostName cse125.ucsd.edu
          Port $SERVER_PORT
          User $SERVER_USER
          IdentityFile ~/.ssh/cse125_id_rsa
          StrictHostKeyChecking yes
          UserKnownHostsFile ~/.ssh/known_hosts
        EOF
        chmod 600 ~/.ssh/config

    - name: Deploy via Rsync
      env:
        REMOTE_PATH: "/var/www/html/class/cse125/www/2025/cse125g3/group3-website"
      run: |
        rsync -avz --delete \
            -e "ssh -F $HOME/.ssh/config" \
            ./ cse125:$REMOTE_PATH/
